development:
  adapter: mysql
  database: cloudcue_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: cloudcue_test
  username: root
  password:

production:
  adapter: mysql
  database: cloudcue_prod
  username: root
  password:
